# Generated by Django 4.2.13 on 2025-02-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('caller', models.CharField(max_length=255, verbose_name='Caller')),
                ('receiver', models.CharField(max_length=255, verbose_name='Receiver')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('caller', models.CharField(max_length=255, verbose_name='Caller')),
                ('receiver', models.CharField(max_length=255, verbose_name='Receiver')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('video_quality', models.CharField(choices=[('HD', 'HD'), ('SD', 'SD'), ('4K', '4K')], default='HD', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
                ('video_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.videocall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
