# Generated by Django 4.2.13 on 2025-02-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer')], default='Credit Card', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('recipient', models.CharField(max_length=255, verbose_name='Recipient')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='podcast.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Invoice Number')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='podcast.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('file_url', models.URLField(verbose_name='Download URL')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='podcast.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True, verbose_name='Model State')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('content', models.TextField(verbose_name='Comment')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='podcast.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
