# Generated by Django 4.2.13 on 2025-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=50, verbose_name='Content Type')),
                ('content_description', models.TextField(blank=True, null=True, verbose_name='Content Description')),
                ('flagged_by', models.CharField(max_length=100, verbose_name='Flagged By')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('title', models.CharField(max_length=200, verbose_name='Report Title')),
                ('content', models.TextField(verbose_name='Report Content')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_progress', 'In Progress')], default='open', max_length=50, verbose_name='Status')),
            ],
        ),
    ]
