# Generated by Django 4.2.13 on 2025-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('name', models.CharField(max_length=200, verbose_name='Algorithm Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('name', models.CharField(max_length=200, verbose_name='Recommendation Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('user_rating', models.FloatField(default=0.0, verbose_name='User Rating')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
    ]
